<script setup lang="ts">
import { onMounted, ref } from 'vue'

interface Doc { id: string; title: string; filename: string; status: string; char_count: number; created_at: string }
interface Memory { id: string; content: string; memory_type: string; importance: number; confidence: number }
interface SearchResult { document_id: string; title: string; content: string; score: number }
const docs = ref<Doc[]>([]); const memories = ref<Memory[]>([]); const results = ref<SearchResult[]>([])
const query = ref(''); const memoryText = ref(''); const uploading = ref(false); const busy = ref(false); const error = ref('')
const types = { fact: '事实', goal: '目标', habit: '习惯', preference: '偏好', skill: '技能', weakness: '薄弱点' }

async function request<T>(path: string, options: RequestInit = {}) { const response = await fetch(`/api/knowledge${path}`, { credentials: 'include', ...options }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error?.message ?? '请求失败'); return body.data as T }
async function load() { [docs.value, memories.value] = await Promise.all([request<Doc[]>('/documents'), request<Memory[]>('/memories')]) }
async function upload(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; uploading.value = true; error.value = ''; const form = new FormData(); form.append('file', file); try { await request('/documents', { method: 'POST', body: form }); await load() } catch (cause) { error.value = cause instanceof Error ? cause.message : '上传失败' } finally { uploading.value = false; (event.target as HTMLInputElement).value = '' } }
async function search() { if (!query.value.trim() || busy.value) return; busy.value = true; try { const data = await request<{ query: string; results: SearchResult[] }>('/search', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query: query.value.trim() }) }); results.value = data.results } catch (cause) { error.value = cause instanceof Error ? cause.message : '搜索失败' } finally { busy.value = false } }
async function addMemory() { if (!memoryText.value.trim()) return; try { await request('/memories', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ content: memoryText.value.trim(), memory_type: 'fact' }) }); memoryText.value = ''; await load() } catch (cause) { error.value = cause instanceof Error ? cause.message : '保存记忆失败' } }
async function removeMemory(id: string) { await request(`/memories/${id}`, { method: 'DELETE' }); memories.value = memories.value.filter(item => item.id !== id) }
async function removeDoc(id: string) { await request(`/documents/${id}`, { method: 'DELETE' }); docs.value = docs.value.filter(item => item.id !== id); results.value = results.value.filter(item => item.document_id !== id) }
onMounted(() => { void load().catch(cause => { error.value = cause instanceof Error ? cause.message : '加载失败' }) })
</script>

<template>
  <section class="knowledge-page">
    <header class="knowledge-heading"><div><p>资料与记忆</p><h1>把学过的内容留在山程里</h1><span>上传资料后，向导会在对话中优先检索相关片段。</span></div><label class="upload-button"><input type="file" accept=".txt,.md,.pdf,.docx" :disabled="uploading" @change="upload">{{ uploading ? '解析中…' : '上传资料' }}</label></header>
    <p v-if="error" class="knowledge-error" role="alert">{{ error }}</p>
    <div class="knowledge-grid">
      <section class="knowledge-section"><div class="section-head"><h2>我的资料</h2><span>{{ docs.length }} 份</span></div><p v-if="!docs.length" class="knowledge-empty">上传一份 TXT、Markdown、PDF 或 DOCX，开始建立个人知识库。</p><ul v-else class="doc-list"><li v-for="doc in docs" :key="doc.id"><div><strong>{{ doc.title }}</strong><small>{{ doc.filename }} · {{ doc.char_count }} 字</small></div><button type="button" aria-label="删除资料" @click="removeDoc(doc.id)">删除</button></li></ul></section>
      <section class="knowledge-section"><div class="section-head"><h2>检索资料</h2><span>仅搜索你的资料</span></div><form class="search-form" @submit.prevent="search"><input v-model="query" placeholder="搜索一个概念或问题…" aria-label="搜索资料"><button type="submit" :disabled="busy">搜索</button></form><div v-if="results.length" class="search-results"><article v-for="result in results" :key="`${result.document_id}-${result.content.slice(0, 12)}`"><strong>{{ result.title }}</strong><small>相关度 {{ result.score }}</small><p>{{ result.content }}</p></article></div><p v-else class="knowledge-empty">搜索结果会显示在这里。</p></section>
      <section class="knowledge-section memory-section"><div class="section-head"><h2>我的记忆</h2><span>{{ memories.length }} 条</span></div><form class="memory-form" @submit.prevent="addMemory"><input v-model="memoryText" maxlength="2000" placeholder="记录一条长期有用的事实…" aria-label="新增记忆"><button type="submit">保存</button></form><ul v-if="memories.length" class="memory-list"><li v-for="memory in memories" :key="memory.id"><div><span class="memory-type">{{ types[memory.memory_type as keyof typeof types] ?? memory.memory_type }}</span><p>{{ memory.content }}</p></div><button type="button" aria-label="删除记忆" @click="removeMemory(memory.id)">删除</button></li></ul><p v-else class="knowledge-empty">向导整理出的长期信息会出现在这里。</p></section>
    </div>
  </section>
</template>

<style scoped>
.knowledge-page{max-width:1180px;margin:0 auto;padding:clamp(2rem,5vw,4rem) clamp(1.25rem,5vw,4rem);color:#173b36}.knowledge-heading{display:flex;justify-content:space-between;align-items:flex-end;gap:2rem;padding-bottom:2rem;border-bottom:1px solid #d6e3d6}.knowledge-heading p{margin:0 0 .5rem;color:#4b8f73;font-size:.78rem;font-weight:700;letter-spacing:.1em}.knowledge-heading h1{margin:0;font-family:"Noto Serif SC",Georgia,serif;font-weight:500;font-size:clamp(1.8rem,4vw,3.2rem)}.knowledge-heading span{display:block;margin-top:.7rem;color:#5f756d}.upload-button,.search-form button,.memory-form button{display:inline-flex;align-items:center;justify-content:center;min-height:2.6rem;padding:0 1rem;border:0;border-radius:8px;color:#fff;background:#285d4e;font:inherit;font-size:.84rem;font-weight:650;cursor:pointer;white-space:nowrap}.upload-button input{position:absolute;width:1px;height:1px;opacity:0}.knowledge-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;margin-top:1.5rem}.knowledge-section{min-width:0;padding:1.2rem;border:1px solid #d4e2d4;border-radius:10px;background:#f8faf4}.memory-section{grid-column:1/-1}.section-head{display:flex;justify-content:space-between;align-items:baseline;gap:1rem;margin-bottom:1rem}.section-head h2{margin:0;font-size:1rem}.section-head span{color:#70877d;font-size:.75rem}.knowledge-empty{margin:0;color:#678075;font-size:.85rem;line-height:1.6}.doc-list,.memory-list{list-style:none;margin:0;padding:0}.doc-list li,.memory-list li{display:flex;justify-content:space-between;align-items:flex-start;gap:1rem;padding:.75rem 0;border-top:1px solid #e0e9df}.doc-list strong,.doc-list small{display:block}.doc-list small{margin-top:.25rem;color:#71887d;font-size:.74rem}.doc-list button,.memory-list button{border:0;color:#8b5247;background:transparent;font:inherit;font-size:.74rem;cursor:pointer}.search-form,.memory-form{display:flex;gap:.5rem}.search-form input,.memory-form input{min-width:0;flex:1;height:2.6rem;padding:0 .75rem;border:1px solid #abc0ae;border-radius:7px;color:#173b36;background:#fff;font:inherit}.search-results{display:grid;gap:.7rem;margin-top:1rem}.search-results article{padding:.8rem;border-radius:8px;background:#edf4eb}.search-results strong{font-size:.82rem}.search-results small{margin-left:.5rem;color:#6b8378;font-size:.7rem}.search-results p{margin:.5rem 0 0;color:#506d61;font-size:.8rem;line-height:1.6;white-space:pre-wrap}.memory-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 1.5rem;margin-top:1rem}.memory-type{color:#4b8f73;font-size:.7rem;font-weight:700}.memory-list p{margin:.3rem 0 0;font-size:.84rem;line-height:1.55}.knowledge-error{color:#9b392c}@media(max-width:760px){.knowledge-heading{display:block}.upload-button{margin-top:1rem}.knowledge-grid{grid-template-columns:1fr}.memory-section{grid-column:auto}.memory-list{grid-template-columns:1fr}}
</style>
